const recipes = [
  {
    id: 'birthday', name: 'Birthday Cake Chili', tag: 'Have your cake. And beans.', time: '40 min', servings: 4,
    description: 'Actual chunks of frosted birthday cake, folded into actual chili. The party has taken a turn.',
    intro: 'Because “bring cake or chili” sounded unnecessarily restrictive.',
    story: 'Everyone says the secret ingredient is love. Mine is half a birthday cake, frosting and all. I cut it into generous chunks so nobody could mistake this for a subtle culinary influence. My friends asked whether it was dinner or dessert. I said yes. Nobody sang a second verse.',
    extra: ['3 cups baked, frosted birthday cake, cut into 1½-inch chunks', '1 tbsp rainbow sprinkles'],
    steps: ['Warm the oil in a pot over medium heat. Add the onion and cook for 5 minutes until softened.', 'Stir in the chili powder, tomatoes, beans, and broth. Simmer uncovered for 25 minutes, stirring occasionally.', 'Remove from the heat. Gently fold in two cups of birthday cake chunks, frosting and all. Keep the pieces big enough that your guests can identify the decision.', 'Ladle into bowls. Crown each serving with the remaining cake chunks and rainbow sprinkles. Dinner now has a birthday.'],
    note: 'Jamie’s tip: Use fully baked cake. Remove candles, wrappers, and decorations first. The frosting is supposed to be there; the plastic dinosaur is not.'
  },
  {
    id: 'pickle', name: 'Dill With It Chili', tag: 'The whole jar. Yes, really.', time: '35 min', servings: 4,
    description: 'Whole pickles. All the brine. One pot with absolutely no interest in compromise.',
    intro: 'We don’t add pickles to the chili. We build the chili around the pickles.',
    story: 'Every great recipe starts with a strong foundation. This one starts with an entire jar of WHOLE dill pickles, brine and all. No draining. No chopping. No opportunity to reconsider. Forget bobbing for apples: this fall we’re bobbing for pickles. With a ladle, obviously. It’s still hot chili, and I’m already on thin ice with the neighborhood committee.',
    ingredients: ['1 jar (24 oz) WHOLE dill pickles, including ALL the brine', '1 small onion, finely diced', '1 tbsp mild chili powder', '1 can (14 oz) diced tomatoes', '2 cans (15 oz each) kidney beans, drained and rinsed', '1 tbsp yellow mustard', '1 tbsp chopped fresh dill'],
    steps: ['Empty the entire jar of whole pickles and every drop of brine into a large pot. This is your starting base. Do not drain, slice, or negotiate.', 'Add the onion, chili powder, tomatoes, beans, and mustard. Stir around the whole pickles like you’re navigating a very sour archipelago.', 'Bring to a gentle simmer over medium heat. Reduce the heat and simmer uncovered for 25–30 minutes, stirring occasionally, until the onion softens.', 'Finish with fresh dill. Ladle into bowls, awarding each guest a whole pickle. Announce that bobbing for pickles is now a spoon sport.'],
    note: 'Jamie’s tip: The brine supplies the liquid and salt. Skip extra salt. Serve with the expression of someone who has done this before.'
  },
  {
    id: 'apple-pie', name: 'As American as Apple Pie Chili', tag: 'Fall’s most confusing tradition', time: '1 hr 30 min', servings: 8,
    description: 'A golden, flaky pie with an apple-chili filling. Fall comfort, with a constitutional identity crisis.',
    intro: 'It’s as American as apple pie. It just has a bean clause.',
    story: 'The leaves were turning, the sweaters were out, and somebody said we needed a festive centerpiece. I brought a lattice-topped apple pie that smelled of cinnamon and quiet rebellion. Beneath that golden crust: apples, beans, tomatoes, and chili spice. It’s everything you love about fall, plus something to discuss on the drive home.',
    ingredients: ['2 unbaked 9-inch pie crusts', '1 tbsp butter', '3 medium firm apples, peeled, cored, and diced', '1 small onion, finely diced', '1 can (15 oz) kidney beans, drained and rinsed', '½ cup thick tomato sauce', '2 tbsp brown sugar', '2 tsp mild chili powder', '½ tsp ground cinnamon', '1 tbsp cornstarch mixed with 1 tbsp cold water', '1 egg, beaten, for brushing the crust'],
    steps: ['Heat the oven to 400°F (200°C). Fit one crust into a 9-inch pie plate. Keep the other crust chilled for the top.', 'Melt the butter in a skillet over medium heat. Cook the apples and onion for 8–10 minutes, stirring, until beginning to soften.', 'Stir in the beans, tomato sauce, brown sugar, chili powder, and cinnamon. Simmer for 5 minutes. Stir in the cornstarch mixture and cook for 2 minutes until thick, with no loose liquid. Let cool for 15 minutes.', 'Spoon the apple-chili filling into the bottom crust. Cut the remaining crust into strips and arrange a lattice on top. Crimp the edges and brush the pastry with beaten egg.', 'Bake on a rimmed baking sheet for 35–45 minutes, until golden with bubbling filling. Shield the edges with foil if they brown too quickly. Rest for 15 minutes before slicing and defending your interpretation of tradition.'],
    note: 'Jamie’s tip: Slice it like a pie, serve it like a pie, and let the first kidney bean do the explaining.'
  },
  {
    id: 'dessert', name: 'The Great Gummy Bear Dessert Chili', tag: 'Looks like dinner. Betrays like dessert.', time: '25 min', servings: 4,
    description: 'Gummy-bear “ground beef,” Candie beans, and spicy chocolate sauce. A bowl-shaped plot twist.',
    intro: 'All the appearance of chili. Absolutely none of the dinner.',
    story: 'I wanted a chili for people who always skip straight to dessert. So I made ground beef out of gummy bears, beans out of jelly beans, and a rich chili sauce out of spicy chocolate. From across the table it looks like dinner. Up close it looks like I should no longer be left alone in the candy aisle.',
    ingredients: ['1 cup red and orange gummy bears', '2 tbsp cocoa powder, divided', '¾ cup red and brown jelly beans', '½ cup heavy cream', '¾ cup semisweet chocolate chips', '¼ tsp ground cinnamon', 'A small pinch of cayenne pepper, to taste', '¼ cup crushed chocolate cookies', 'Vanilla yogurt or whipped cream, for the “sour cream”'],
    steps: ['Finely snip the gummy bears with clean kitchen scissors. Toss the sticky pieces with 1 tablespoon cocoa powder and the crushed cookies until they resemble little crumbles of browned ground beef. No actual beef enters this situation.', 'Warm the cream in a small saucepan over low heat until steaming, without boiling. Remove from the heat and stir in the chocolate chips until smooth.', 'Whisk in the remaining cocoa, cinnamon, and a small pinch of cayenne. You now have spicy chocolate “chili sauce.” Let it cool until barely warm so the gummy beef keeps its questionable shape.', 'Fold in the jelly beans and most of the gummy-bear crumbles. Divide among four small bowls, then scatter the remaining crumbles on top for maximum chili credibility.', 'Add a dollop of vanilla yogurt or whipped cream as “sour cream.” Serve as dessert and enjoy the moment everyone realizes their beans are candy.'],
    note: 'Jamie’s tip: Start tiny with the cayenne. The surprise is supposed to be gummy-bear beef, not a five-alarm chocolate emergency.'
  },
  {
    id: 'espresso', name: 'The 8 A.M. Espresso Chili', tag: 'Breakfast is a mindset', time: '40 min', servings: 4,
    description: 'Smoky beans meet coffee and cocoa. Finally, a chili that could have been a meeting.',
    intro: 'For mornings when a cup of coffee just doesn’t contain enough kidney beans.',
    story: 'I wanted a breakfast that said “I have my life together,” but also “I own a suspiciously large stockpot.” Enter espresso chili. The coffee brings depth, the cocoa brings richness, and serving it in a mug brings questions I am not prepared to answer.',
    extra: ['¼ cup brewed decaf coffee', '1 tsp unsweetened cocoa powder', '1 tbsp brown sugar', 'Crushed tortilla chips, to serve'],
    steps: ['Heat the oil over medium heat. Cook the onion for 5 minutes.', 'Stir in the chili powder and cocoa. Add tomatoes, beans, broth, coffee, and brown sugar.', 'Simmer uncovered for 25–30 minutes, stirring occasionally, until thickened.', 'Serve with tortilla chips and the confidence of someone who absolutely meant to do this.'],
    note: 'Jamie’s tip: Decaf keeps the joke in the flavor. No one needs their beans vibrating.'
  }
];
const base=['1 tbsp olive oil','1 small onion, diced','1 tbsp mild chili powder','1 can (14 oz) diced tomatoes','2 cans (15 oz each) kidney beans, drained and rinsed','½ cup vegetable broth'];
const grid=document.querySelector('#recipe-grid');
grid.innerHTML=recipes.map((r,i)=>`<a class="card" href="#recipe/${r.id}"><div class="card-top"><span class="card-number">0${i+1}</span><span class="tag">${r.tag}</span></div><h3>${r.name}</h3><p>${r.description}</p><div class="card-bottom"><span>${r.time} · ${r.servings} servings</span><strong>Get the recipe ↗</strong></div></a>`).join('');
function route(){const id=location.hash.startsWith('#recipe/')?location.hash.slice(8):null;const r=recipes.find(r=>r.id===id);const view=document.querySelector('#recipe-view');document.querySelector('#home').hidden=!!r;view.hidden=!r;if(r){document.title=`${r.name} — The Unhinged Ladle`;view.innerHTML=`<article class="article"><a class="back" href="#recipes">← Back to the recipes</a><p class="eyebrow" style="margin-top:30px">${r.tag}</p><h1>${r.name}</h1><p class="dek">${r.intro}</p><p class="byline">By Jamie Ladle · Filed under: questionable decisions</p><a class="button" href="#instructions">Jump to recipe</a><p class="story">${r.story}</p><section class="recipe-box" id="instructions"><h2>${r.name}</h2><div class="recipe-meta"><span>Total: ${r.time}</span><span>Serves: ${r.servings} brave friends</span><span>Difficulty: emotionally moderate</span></div><div class="recipe-columns"><div><h3>Ingredients</h3><ul>${(r.ingredients ?? [...base,...r.extra]).map(x=>`<li>${x}</li>`).join('')}</ul></div><div><h3>Let’s make a decision.</h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div></div><p class="recipe-note">${r.note}</p><button class="button" type="button" id="print-recipe">Print recipe</button></section><p class="recipe-note">From a satirical kitchen. These combinations are jokes, not tested recipes. Check ingredients for your guests’ allergies.</p></article>`;document.querySelector('#print-recipe').onclick=()=>window.print();view.querySelector('a[href="#instructions"]').onclick=e=>{e.preventDefault();document.querySelector('#instructions').scrollIntoView({behavior:'smooth'});};window.scrollTo(0,0);}else{document.title='The Unhinged Ladle — Good food. Questionable decisions.';if(location.hash){requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());}}}
window.addEventListener('hashchange',route);route();
